version: '3'
services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    ports:
      # Expose 9999 for localhost only
      - "127.0.0.1:9999:8080"
    volumes:
      - './data/blazegraph/bigdata.jnl:/var/lib/jetty/bigdata.jnl'
      - './scripts/assets:/assets'
