version: '3'
services:
  blazegraph:
    # Build our own image to get up-to-date packages, especially SSL
    # as outdated packages result in "ExecutionException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure" with query.wikidata.org
    build:
      context: ./blazegraph/2.1.5
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      # Expose 9999 for localhost only
      - "127.0.0.1:9999:8080"
    volumes:
      - './scripts/assets:/assets'
      # This was triggering the creation of bigdata.jnl as a directory,
      # so better let Docker handle that volume, we can always rebuild the data from entities dumps
      # - './data/blazegraph/bigdata.jnl:/var/lib/jetty/bigdata.jnl'
