#!/usr/bin/env bash

blazegraph_host=http://localhost:9999

post_ttl_file(){
  namespace=$1
  file_path=$2
  curl "${blazegraph_host}/bigdata/namespace/${namespace}/sparql" -H 'Content-Type: application/x-turtle' -d@"./${2}" &&
  echo "namespace: ${namespace} - file: ${file_path}"
}

[ -e entities_with_seeds.ttl ] || {
  curl https://dumps.inventaire.io/inv/latest/entities_with_seeds.ttl.gz | gzip -d > entities_with_seeds.ttl
}

# Using the default namespace - kb - as no way to create one from the API could be found
post_ttl_file kb entities_with_seeds.ttl
