#!/usr/bin/env bash
cat ./templates/query_service.nginx.template |
  sed "s@INVENTAIRE_QUERY_GUI_PATH@${INVENTAIRE_QUERY_GUI_PATH}@" |
  # Adding to the default file as LetsEncrypt certbox won't work if it's in a separated file
  sudo tee -a /etc/nginx/sites-enabled/default
sudo nginx -s reload
